[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
auto_detect_remappings = false

[profile.default.fuzz]
runs = 128

[fmt]
line_length = 120
